services:
  database:
    image: mongo:latest
    container_name: mongo_db
    networks:
      - app_net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:?Environment variable MONGO_ROOT_USER is required}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:?Environment variable MONGO_ROOT_PASSWORD is required}
    volumes:
      - mongo_data:/data/db

  dash-app:
    build: ./app
    container_name: dash_app
    networks:
      - app_net
    ports:
      - "8050:${PORT:-8050}"
    environment:
      - FLASK_SKIP_DOTENV=true ## disable flask .env tip
      - APP_ENV=${APP_ENV:-production}
      - BASE_PATH=${BASE_PATH:-/}
      - MONGO_USER=${MONGO_ROOT_USER:?Variable missing}
      - MONGO_PASS=${MONGO_ROOT_PASSWORD:?Variable missing}
    depends_on:
      - database

volumes:
  mongo_data:

networks:
  app_net:
    driver: bridge